### ISSUE TITLE
Parameters are not listed as variable dependencies

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-parsers#19]
https://legislation.openfisca.fr/variables/preetu uses `ir.credits_impot.preetu.taux`, `ir.credits_impot.preetu.max`, etc. but those are not listed, neither in https://api.openfisca.fr/api/1/variables?name=preetu

**Comment by MattiSG** [comment]
@fpagnoux This is supposedly fixed in openfisca/openfisca-france#566, yet https://github.com/openfisca/legislation-explorer/issues/19 still seems to exist. Is it only a matter of the legislation explorer not being up to date?
@cbenz when was the last update of the online explorer?

**Comment by cbenz** [comment]
Yesterday :-)

But the problem still exists.

I think that GitHub closed this issue which was mentioned in openfisca/openfisca-france#566 in a task list, but not checked!

I reopen.

**Comment by fpagnoux** [comment]
This package is deprecated. This issue won't be addressed, sorry.
